@url = http://localhost:5241

// Запросы соревнования start

GET {{url}}/api/competitions/
Accept: application/json

###

GET {{url}}/api/competitions/f47ac10b-58cc-4372-a567-0e02b2c3d410

###

POST {{url}}/api/competitions
Content-Type: application/json

{
  "Name": "Test2",
  "Date": "",
  "Location": "Testing2",
  "SportType": "Testing2"
}

###

PUT {{url}}//api/competitions/50744159-2653-414d-b961-2e9661ce2120
Content-Type: application/json

{
  "Name": "Test4",
  "Date": "2024-07-01T01:00:00",
  "Location": "",
  "SportType": ""
}

###

DELETE {{url}}//api/competitions/50744159-2653-414d-b961-2e9661ce2120

###

// Запросы соревнования end

// Запросы результата start

GET {{url}}//api/results
Accept: application/json

###

GET {{url}}//api/results/763c3b46-7a52-410a-a496-1b519c339cc2
Accept: application/json

###

GET {{url}}//api/competitions/f47ac10b-58cc-4372-a567-1e12b2c3d470/results
Accept: application/json

###

POST {{url}}//api/results
Content-Type: application/json

{
  "CompetitionId": "",
  "ParticipantName": "Тест",
  "Place": 0,
  "Score": 0
}

###

PUT {{url}}//api/results/763c3b46-7a52-410a-a496-1b609c339cc2
Content-Type: application/json

{
  "CompetitionId": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
  "ParticipantName": "",
  "Place": 0,
  "Score": 0
}

###

DELETE {{url}}//api/results/763c3b46-7a52-410a-a496-1b209c339cc2

###

// Запросы результата end